# This is a test workflow for opencdms-test-data
name: tests
# Controls when the workflow will run
on: [push]

jobs:
  matrix-setup:
    strategy:
      matrix:
        os: [windows-latest,macos-latest,ubuntu-latest]
        py-version: ['3.7','3.8','3.9','3.10','3.11']
    runs-on: ${{matrix.os}}
    steps:
      - name: Support longpaths
        if: ${{matrix.os == 'windows-latest'}}
        shell: cmd
        run: git config --global core.longpaths true
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.py-version }}
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.py-version }}

      # Runs a single command using the runners shell
      - name: Installs necessary dependencies
        run: pip3 install -r requirements_dev.txt

      - name: Set env file for windows
        if: ${{matrix.os == 'windows-latest'}}
        shell: cmd
        run: copy .env.sample .env
      
      - name: Set env file for linux shell
        if: ${{matrix.os == 'ubuntu-latest'}} || ${{matrix.os == 'macos-latest'}} 
        shell: bash
        run: cp .env.sample .env
        
      # Runs a set of commands using the runners shell
      - name: Runs tests
        run: pytest tests